name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and pull + restart
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: tusher16
          key: ${{ secrets.SSH_KEY }}
          port: 2024
          script: |
            cd /home/tusher16/rag-studio
            git pull origin main
            docker compose up --build -d